services:
  db:
    container_name: db
    image: mysql
    restart: always
    networks:
      - backend
    volumes:
      - db:/var/lib/mysql
      - ./init/db/init.sql:/docker-entrypoint-initdb.d/01.sql
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
  migrate:
    container_name: migrate
    restart: on-failure:10
    build:
      context: ./server/prisma
      dockerfile: ./Dockerfile
    networks:
      - backend
    depends_on:
      - db
    environment:
      - MAIN_DATABASE_URL=${MAIN_DATABASE_URL}
      - MAIN_SHADOW_DATABASE_URL=${MAIN_SHADOW_DATABASE_URL}
      - ANALYTICS_DATABASE_URL=${ANALYTICS_DATABASE_URL}
      - ANALYTICS_SHADOW_DATABASE_URL=${ANALYTICS_SHADOW_DATABASE_URL}
      - STATIC_DATABASE_URL=${STATIC_DATABASE_URL}
      - STATIC_SHADOW_DATABASE_URL=${STATIC_SHADOW_DATABASE_URL}
  cache:
    container_name: cache
    restart: always
    image: redis
    volumes:
      - cache:/etc/redis
    networks:
      - backend
    environment:
      - REDIS_PORT=6379
      - REDIS_DATABASES=1
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      timeout: 10s
      retries: 5
  api:
    container_name: api
    restart: on-failure:10
    networks:
      - backend
    build:
      context: ./server
      dockerfile: ./Dockerfile
      args:
        - MAIN_DATABASE_URL=${MAIN_DATABASE_URL}
        - MAIN_SHADOW_DATABASE_URL=${MAIN_SHADOW_DATABASE_URL}
        - ANALYTICS_DATABASE_URL=${ANALYTICS_DATABASE_URL}
        - ANALYTICS_SHADOW_DATABASE_URL=${ANALYTICS_SHADOW_DATABASE_URL}
        - STATIC_DATABASE_URL=${STATIC_DATABASE_URL}
        - STATIC_SHADOW_DATABASE_URL=${STATIC_SHADOW_DATABASE_URL}
    depends_on:
      - db
      - migrate
      - cache
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${API_PORT}
      - REDIS_URL=${REDIS_URL}
      - MAIN_DATABASE_URL=${MAIN_DATABASE_URL}
      - MAIN_SHADOW_DATABASE_URL=${MAIN_SHADOW_DATABASE_URL}
      - ANALYTICS_DATABASE_URL=${ANALYTICS_DATABASE_URL}
      - ANALYTICS_SHADOW_DATABASE_URL=${ANALYTICS_SHADOW_DATABASE_URL}
      - STATIC_DATABASE_URL=${STATIC_DATABASE_URL}
      - STATIC_SHADOW_DATABASE_URL=${STATIC_SHADOW_DATABASE_URL}
    ports:
      - ${API_PORT}:${API_PORT}
    expose:
      - ${API_PORT}
    volumes:
      - api:/usr/app

volumes:
  db:
  cache:
  api:
networks:
  backend:
