spectaql:
  oneFile: true
  targetDir: ./docs
introspection:
  url: http://localhost:3000/graphql
info:
  title: Restaurant Orders API Reference
  description: API for making your Restaurant more effective!
